# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Articles',
        ),
    ]
