# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0005_auto_20180822_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 8, 22, 15, 2, 7, 710663, tzinfo=utc))),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlehits', to='articles.Article')),
            ],
        ),
    ]
