# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180822_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_session_key', models.CharField(max_length=40)),
                ('start', models.DateTimeField(default=datetime.datetime(2018, 8, 22, 17, 43, 32, 916694, tzinfo=utc))),
                ('end', models.DateTimeField(default=None)),
            ],
        ),
        migrations.RenameField(
            model_name='articlehit',
            old_name='session',
            new_name='custom_session_key',
        ),
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 22, 17, 43, 32, 916694, tzinfo=utc)),
        ),
    ]
