# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180822_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 22, 18, 22, 7, 686438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='articlehit',
            name='custom_session_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SessionBind'),
        ),
        migrations.AlterField(
            model_name='sessionbind',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 22, 18, 22, 7, 685438, tzinfo=utc)),
        ),
    ]
