# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180822_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlehit',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlehit',
            name='custom_session_key',
        ),
        migrations.DeleteModel(
            name='ArticleHit',
        ),
    ]
